apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # labels of deployment resource
  labels:
    app: frontend 
    tier: web
    purpose: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend 
      tier: web
      purpose: expense
  template:
    metadata:
      labels:
        app: frontend 
        tier: web
        purpose: expense  
    spec:
      containers:
      - name: frontend
        image: rakeshreddy07/frontend:1.1.0
---
kind: Service
apiVersion: v1
metadata:
  name: frontend 
  namespace: expense
spec: 
  type: LoadBalancer
  selector:
    app: frontend 
    tier: web
    purpose: expense  
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 8080