apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # labels of deployment resource
  labels:
    app: mysql 
    tier: mysql 
    purpose: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql 
      tier: mysql 
      purpose: expense
  template:
    metadata:
      labels:
        app: mysql 
        tier: mysql 
        purpose: expense  
    spec:
      containers:
      - name: mysql
        image: rakeshreddy07/mysql:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: mysql 
spec: 
  selector:
    app: mysql 
    tier: mysql 
    purpose: expense  
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306